### ISSUE TITLE
CPU&GPU

### ISSUE THREAD

**Issue by wzw1998** [cshizhe/asg2cap#15]
我想请问一下，为什么训练的时候CPU占用率很高接近90%，但是GPU没有用到，torch.cuda.is_available()是True的，希望您有空回复一下。

**Comment by yudzhang** [comment]
请问一下您是跑起来了吗，我遇到一个问题想问一下
Traceback (most recent call last):
  File "asg2caption.py", line 146, in <module>
    main()
  File "asg2caption.py", line 36, in main
    model_cfg.load(opts.model_cfg_file)
  File "../../framework/configbase.py", line 59, in load
    with open(cfg_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/model.json'

**Comment by wzw1998** [comment]
这个是我的博客https://blog.csdn.net/qq_41115379/article/details/111757411
你可以看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cshizhe/asg2cap"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 晚上9:53
收件人:&nbsp;"cshizhe/asg2cap"<asg2cap@noreply.github.com&gt;;
抄送:&nbsp;"布布龙"<1452682438@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cshizhe/asg2cap] CPU&amp;GPU (#15)





 
请问一下您是跑起来了吗，我遇到一个问题想问一下
 Traceback (most recent call last):
 File "asg2caption.py", line 146, in 
 main()
 File "asg2caption.py", line 36, in main
 model_cfg.load(opts.model_cfg_file)
 File "../../framework/configbase.py", line 59, in load
 with open(cfg_file) as f:
 FileNotFoundError: [Errno 2] No such file or directory: '/model.json'
